package io.customer.messagingpush

import com.google.firebase.messaging.RemoteMessage
import io.customer.base.internal.InternalCustomerIOApi
import io.customer.messagingpush.util.PushTrackingUtil
import io.customer.sdk.util.DateUtil
import io.customer.sdk.util.Logger

/**
 * Helper class to hold all message processing tasks at a single place.
 */
@InternalCustomerIOApi
interface CustomerIOFirebaseMessageProcessor {
    /**
     * Should be called whenever push notification is received. The method is
     * responsible for making sure that a CIO notification is processed only one
     * time even if the listeners are invoked multiple times.
     *
     * @param remoteMessage message received from FCM.
     * @param handler callback to process the message, the call is ignored if the
     * notification was processed previously.
     * @return true if the notification was processed previously, false if the
     * notification is not from Customer.io; else returns the value received from
     * [handler].
     */
    fun onMessageReceived(
        remoteMessage: RemoteMessage,
        handler: () -> Boolean
    ): Boolean
}

@InternalCustomerIOApi
internal class CustomerIOFirebaseMessageProcessorImpl(
    private val logger: Logger,
    private val dateUtil: DateUtil
) : CustomerIOFirebaseMessageProcessor {
    /**
     * Holds message id of last handled notification against CIO delivery token.
     * This helps deciding between whether the notification was previously processed or not.
     */
    private val deliveryTokenToMessageId = mutableMapOf<String, String>()

    override fun onMessageReceived(remoteMessage: RemoteMessage, handler: () -> Boolean): Boolean {
        val cioDeliveryToken = remoteMessage.data[PushTrackingUtil.DELIVERY_TOKEN_KEY]
        // Skip processing the notification if there isn't any Customer.io delivery token
        if (cioDeliveryToken.isNullOrBlank()) {
            logger.info("Not a CIO push notification, skipping processing")
            return false
        }

        val isHandled: Boolean
        // Make sure to process same notification only one time irrespective of number of callbacks
        // invoked for it
        synchronized(this) {
            val currentMessageId = remoteMessage.messageId
            val lastMessageId = deliveryTokenToMessageId[cioDeliveryToken]
            // Message ID is generated by FCM and helps us handling one notification only once
            // If the ID is null, we'll fallback to the behavior suggested by the config
            if (lastMessageId.isNullOrBlank() || lastMessageId != currentMessageId) {
                logger.info("CIO push notification processing with token $cioDeliveryToken, message id: $currentMessageId")
                isHandled = handler()
                if (!currentMessageId.isNullOrBlank()) {
                    deliveryTokenToMessageId[cioDeliveryToken] = currentMessageId
                }
            } else {
                logger.info("CIO push notification already processed with token $cioDeliveryToken, message id: $currentMessageId")
                isHandled = true
            }
        }
        return isHandled
    }
}
