name: Build sample app for SDK release
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-sample-apps:
    uses: ./.github/workflows/reusable_build_sample_apps.yml
    with:
      use_latest_sdk_version: true
    secrets: inherit
