name: Deploy git tag

# Only run after a pull request has been merged. This is because
# bot account runs write operations on the github repo to push a tag. 
on:
  push:
    branches: [ main, beta, alpha ]

jobs:
  deploy-tag:
    name: Deploy git tag
    runs-on: ubuntu-latest
    steps:
      - name: semantic-release setup
        uses: levibostian/action-semantic-release-justwork@v1
      - name: Deploy git tag via semantic-release 
        uses: cycjimmy/semantic-release-action@v3
        id: semantic-release
        with: 
          dry_run: false
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 18
          extra_plugins: |
            conventional-changelog-conventionalcommits@4
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/github@8
            @semantic-release/exec@6
        env:
          # Needs to push git commits to repo. Needs write access. 
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_BOT_TOKEN }}

      - name: Prepare to sync branches 
        run: |
          git config user.email "frontend@customer.io"
          git config user.name "Ami CI"
      - name: Copy commits into develop after main deployment 
        uses: levibostian/action-sync-branches@v1
        with:
          behind: develop
          ahead: main 
          githubToken: ${{ secrets.WRITE_ACCESS_BOT_TOKEN }}
    
      - name: Notify team of git tag being created 
        uses: openhousepvt/slack@v1.3.2
        if: steps.semantic-release.outputs.new_release_published == 'true'
        with:
          status: 'in progress' # in progress status because need to now deploy SDK to maven central for full deployment 
          version: ${{ steps.semantic-release.outputs.new_release_version }}
          platform: 'Android SDK - git tag created'
          channel: '#squad-mobile'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFY_RELEASES_WEBHOOK_URL }}