name: Instrumentation tests

on: [push, pull_request]

jobs:
  instrumentation-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [samples/kotlin_compose]
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Start emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        script: echo "Emulator started"

    - name: Run instrumentation tests
      run: ./gradlew :${{ matrix.module }}:connectedAndroidTest

    - name: Publish test results
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report_paths: './${{ matrix.module }}/build/outputs/androidTest-results/connected/TEST-*.xml'
