name: Instrumentation tests

on: [push, pull_request]

jobs:
  instrumentation-test:
    runs-on: macos-latest
    timeout-minutes: 45
    strategy:
      matrix:
        sample: [kotlin_compose, java_layout]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Gradle cache
      uses: gradle/gradle-build-action@v2

    - name: Start emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        ram-size: 4096M
        emulator-boot-timeout: 12000
        target: default
        arch: x86
        emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160
        profile: Nexus 6
        script: ./gradlew :samples:${{ matrix.sample }}:connectedDebugAndroidTest

    - name: Publish test results
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report_paths: 'samples/${{ matrix.sample }}/build/outputs/androidTest-results/connected/TEST-*.xml'
