name: Instrumentation tests

on: [push, pull_request]

jobs:
  instrumentation-test:
    runs-on: macos-latest
    strategy:
      matrix:
        module: [samples/kotlin_compose]
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Start emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: google_apis
        arch: x86
        profile: Nexus 6
        script: ./gradlew :samples:kotlin_compose:connectedAndroidTest

    - name: Publish test results
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report_paths: './${{ matrix.module }}/build/outputs/androidTest-results/connected/TEST-*.xml'
